image: repositories/basic-singularity-images:debian-build-tools




build:
    artifacts:
        paths:
           - plot.png

        when: always
        
    tags:
      - singularity
    variables:
    before_script:
      - apt update && apt install -y ninja-build python3 python3-pip
      - apt install -y libsdl2-mixer-dev libsdl2-ttf-dev libsodium-dev
      - git submodule init
      - git submodule update
    script:
      - wget https://raw.githubusercontent.com/antmicro/sargraph/master/sargraph.py
      - chmod +x sargraph.py
      - ./sargraph.py chart start
      - pip3 install -r requirements.txt
      - pushd tools/cmake
      - pwd
      - ls
      - ./configure
      - make install
      - popd
      - mkdir build
      - pushd build
      - git clone https://github.com/diasurgical/devilutionx
      - pushd devilutionx/build
      - cmake .. -G "Ninja" | ../../../tools/dep2yaml/dep2yaml.py > ../../../build.yml
      - popd
      - popd
      - ./raclient.py build.yml devilutionx --no-server
      - ./sargraph.py chart stop

